const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.LocalStorage,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.MoveTo,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Touch.Exps.TouchCount,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.AddRemoveAnimationFrame,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.DragnDrop.Acts.Drop,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.PickByComparison
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{Mouse: 0},
	{Touch: 0},
	{settings: 0},
	{AJAX: 0},
	{LocalStorage: 0},
	{type: 0},
	{number: 0},
	{available: 0},
	{lang: 0},
	{sf: 0},
	{frogs: 0},
	{Fade: 0},
	{MoveTo: 0},
	{SFanim: 0},
	{Audio: 0},
	{Ad: 0},
	{panelcollection: 0},
	{panelcollection2: 0},
	{panelcollection3: 0},
	{paneldefeat: 0},
	{paneldefeat2: 0},
	{Tween: 0},
	{panelfrog: 0},
	{panelFrogBar: 0},
	{Anchor: 0},
	{panelhp: 0},
	{panelscore: 0},
	{paneltxt: 0},
	{Settings: 0},
	{obj_btn: 0},
	{find: 0},
	{obj_find: 0},
	{obj_level: 0},
	{bg: 0},
	{hint: 0},
	{cross: 0},
	{add: 0},
	{shadow: 0},
	{frog: 0},
	{animationtap: 0},
	{effectfind: 0},
	{buttonloupe: 0},
	{Sine: 0},
	{tutorial: 0},
	{panelwin: 0},
	{ramka: 0},
	{Sprite: 0},
	{Rotate: 0},
	{star: 0},
	{panelwin2: 0},
	{circle: 0},
	{frogCollection: 0},
	{buttonsound: 0},
	{buttonmusic: 0},
	{iconalert: 0},
	{DragDrop: 0},
	{scroll: 0},
	{bg2: 0},
	{panelshop: 0},
	{buttonshop: 0},
	{buttonshop2: 0},
	{panelshopoffer: 0},
	{TouchID: 0},
	{idStr: 0},
	{buttonbuy_shop: 0},
	{panelshopoffer2: 0},
	{iconshopoffer: 0},
	{inap: 0},
	{purchased: 0},
	{buttonrandomlvl: 0},
	{panel_scale_: 0},
	{button_scale_: 0},
	{LastY: 0},
	{LastX: 0},
	{zoommaxW: 0},
	{zoommaxH: 0},
	{Scroll_End: 0},
	{hintonLevel: 0},
	{TS_Speed_Scroll: 0},
	{TS_Speed_Scroll_End: 0},
	{touchid: 0},
	{TouchDistance: 0},
	{StartScaleZoom: 0},
	{currentdistance: 0},
	{lock: 0},
	{reward: 0},
	{timerCombo: 0},
	{collection: 0},
	{animation: 0},
	{randomLevel: 0},
	{sum: 0},
	{LastPurchaseName: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	settings: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	sf: class extends self.ISpriteFontInstance {},
	frogs: class extends self.IArrayInstance {},
	SFanim: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	Ad: class extends self.IArrayInstance {},
	panelcollection: class extends self.ISpriteInstance {},
	panelcollection2: class extends self.ISpriteInstance {},
	panelcollection3: class extends self.ISpriteInstance {},
	paneldefeat: class extends self.ISpriteInstance {},
	paneldefeat2: class extends self.ISpriteInstance {},
	panelfrog: class extends self.ISpriteInstance {},
	panelFrogBar: class extends self.ITiledBackgroundInstance {},
	panelhp: class extends self.ISpriteInstance {},
	panelscore: class extends self.ISpriteInstance {},
	paneltxt: class extends self.ISpriteInstance {},
	obj_btn: class extends self.ISpriteInstance {},
	obj_find: class extends self.ISpriteInstance {},
	obj_level: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	hint: class extends self.ISpriteInstance {},
	cross: class extends self.ISpriteInstance {},
	shadow: class extends self.ISpriteInstance {},
	frog: class extends self.ISpriteInstance {},
	animationtap: class extends self.ISpriteInstance {},
	effectfind: class extends self.ISpriteInstance {},
	buttonloupe: class extends self.ISpriteInstance {},
	tutorial: class extends self.ISpriteInstance {},
	panelwin: class extends self.ISpriteInstance {},
	ramka: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	panelwin2: class extends self.ISpriteInstance {},
	circle: class extends self.ISpriteInstance {},
	frogCollection: class extends self.ISpriteInstance {},
	buttonsound: class extends self.ISpriteInstance {},
	buttonmusic: class extends self.ISpriteInstance {},
	iconalert: class extends self.ISpriteInstance {},
	scroll: class extends self.ISpriteInstance {},
	bg2: class extends self.ISpriteInstance {},
	panelshop: class extends self.ISpriteInstance {},
	buttonshop: class extends self.ISpriteInstance {},
	buttonshop2: class extends self.ISpriteInstance {},
	panelshopoffer: class extends self.ISpriteInstance {},
	buttonbuy_shop: class extends self.ISpriteInstance {},
	panelshopoffer2: class extends self.ISpriteInstance {},
	iconshopoffer: class extends self.ISpriteInstance {},
	purchased: class extends self.ISpriteInstance {},
	buttonrandomlvl: class extends self.ISpriteInstance {},
	panel_scale_: class extends self.ISpriteInstance {},
	button_scale_: class extends self.ISpriteInstance {}
}